apiVersion: v1
kind: Service
metadata:
  name: dk-data-metering-proxy
  labels:
    app: postgrest
    app.kubernetes.io/name: dk-data
    app.kubernetes.io/component: metering-proxy
    app.kubernetes.io/part-of: dk-data
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: proxy
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: postgrest
