apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: minio-backup-credentials
  labels:
    app: pg-backup
    app.kubernetes.io/part-of: dk-data
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: minio-backup-credentials
    namespace: ""  # Set by overlay
  secrets:
    - MINIO_ACCESS_KEY
    - MINIO_SECRET_KEY
