apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config
  labels:
    app: postgrest
    app.kubernetes.io/name: postgrest
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: dk-data
data:
  PGRST_DB_SCHEMAS: "api,mol_api,mol_silver,mol_gold,hcs_silver,hcs_gold,ind_silver,ind_gold,hcp_silver,hcp_gold,hcs_agents,mol_agents,agents,xenon,meta,mart,scoring,staging,application"
  PGRST_DB_ANON_ROLE: "web_anon"
  PGRST_SERVER_PORT: "3000"
  PGRST_LOG_LEVEL: "info"
  PGRST_DB_POOL: "30"
  PGRST_DB_POOL_ACQUISITION_TIMEOUT: "10"
  PGRST_DB_STATEMENT_TIMEOUT: "30s"
  PGRST_OPENAPI_MODE: "disabled"
  PGRST_OPENAPI_SERVER_PROXY_URI: ""
