apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: minio-backup-credentials
  labels:
    app: pg-backup
    app.kubernetes.io/part-of: dk-data
    app.kubernetes.io/managed-by: doppler-operator
spec:
  tokenSecret:
    name: doppler-token-secret
    key: serviceToken
  project: dk-data-applications
  config: prd
  managedSecret:
    name: minio-backup-credentials
    type: Opaque
  resyncSeconds: 300
