apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dk-data-staging
  namespace: argocd
  labels:
    tenant: dk-data
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dk-data

  source:
    repoURL: https://github.com/data-kinetic/dk-data-fe.git
    targetRevision: staging
    path: k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: dk-data-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
