"""Ingestion source modules."""

__all__ = [
    'cms_inpatient',
    'cms_hospital_info',
    'cms_cost_reports',
    'acc_tvc',
    'hrsa',
    'pubmed',
    'ema_regulatory',
    'openalex_ci',
    'drugbank',
    'uspto_patents',
    'journal_rss',
    'uspto_ci',
    'hta_bodies',
    'epo_ops',
    'cochrane',
    'medical_news',
    'sec_edgar',
    'uniprot',
    'pdb',
    'orcid',
    'uspto_trademarks',
    'euipo_trademarks',
    'who_icd',
    'bindingdb',
    'sider',
    'europepmc',
    'nih_reporter',
    'cms_geographic_variation',
    'cms_part_d_prescriber',
    'rxnorm',
    'who_inn',
    'pharmgkb',
    'kegg_drug',
    'tdc_admet',
]
