"""Ingestion source modules."""

__all__ = [
    'cms_inpatient',
    'cms_hospital_info',
    'cms_cost_reports',
    'acc_tvc',
    'hrsa',
    'pubmed',
    'ema_regulatory',
    'openalex_ci',
    'drugbank',
    'uspto_patents',
    'journal_rss',
    'uspto_ci',
    'hta_bodies',
    'epo_ops',
    'cochrane',
    'medical_news',
    'sec_edgar',
    'uniprot',
    'pdb',
    'uspto_trademarks',
    'euipo_trademarks',
]
