apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dk-data
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: dk-data production deployment

  sourceRepos:
    - https://github.com/data-kinetic-projects/dk-data-FE.git

  destinations:
    - namespace: dk-data-prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true
