#!/usr/bin/env bash
set -euo pipefail

# create-new-feature.sh — Create a feature branch and spec directory
#
# Usage: create-new-feature.sh "<brief_or_description>" [--json] [--short-name "<name>"] [--timestamp] "<description>"
#
# Creates:
#   - A new git branch: feature/<number>-<short-name>
#   - A spec directory: .dk/specs/<number>-<short-name>/
#   - A spec file: .dk/specs/<number>-<short-name>/spec.md
#   - A checklists dir: .dk/specs/<number>-<short-name>/checklists/

DK_DIR=".dk"
SPECS_DIR="$DK_DIR/specs"
CONFIG_FILE="$DK_DIR/config.yaml"

JSON_OUTPUT=false
SHORT_NAME=""
TIMESTAMP_MODE=false
DESCRIPTION=""
BRIEF_PATH=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --json) JSON_OUTPUT=true; shift ;;
    --short-name) SHORT_NAME="$2"; shift 2 ;;
    --timestamp) TIMESTAMP_MODE=true; shift ;;
    *)
      if [[ -z "$BRIEF_PATH" ]]; then
        BRIEF_PATH="$1"
      else
        DESCRIPTION="$1"
      fi
      shift
      ;;
  esac
done

if [[ -z "$SHORT_NAME" ]]; then
  echo "Error: --short-name is required" >&2
  exit 1
fi

# Determine feature number
if [[ "$TIMESTAMP_MODE" == true ]]; then
  FEATURE_NUM=$(date +"%Y%m%d-%H%M%S")
else
  # Find the next sequential number
  LAST_NUM=0
  if [[ -d "$SPECS_DIR" ]]; then
    for dir in "$SPECS_DIR"/*/; do
      if [[ -d "$dir" ]]; then
        NUM=$(basename "$dir" | grep -oE '^[0-9]+' || echo "0")
        if [[ "$NUM" -gt "$LAST_NUM" ]]; then
          LAST_NUM="$NUM"
        fi
      fi
    done
  fi
  FEATURE_NUM=$(printf "%03d" $((LAST_NUM + 1)))
fi

FEATURE_NAME="${FEATURE_NUM}-${SHORT_NAME}"
FEATURE_DIR="$SPECS_DIR/$FEATURE_NAME"
BRANCH_NAME="feature/$FEATURE_NAME"
SPEC_FILE="$FEATURE_DIR/spec.md"

# Create directories
mkdir -p "$FEATURE_DIR/checklists"
mkdir -p "$FEATURE_DIR/memory"

# Create spec memory files
cat > "$FEATURE_DIR/memory/context.md" << MEMEOF
# Feature: $SHORT_NAME

## Key Constraints
Tags:

## Important Context

## Open Questions
MEMEOF

cat > "$FEATURE_DIR/memory/blockers.md" << MEMEOF
# Blockers & Workarounds

<!-- Append blockers encountered during implementation -->
MEMEOF

cat > "$FEATURE_DIR/memory/changelog.md" << MEMEOF
# Changelog

## Session $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- Feature created: $SHORT_NAME
MEMEOF

# Create branch
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME" 2>/dev/null || true

# Create initial spec file
cat > "$SPEC_FILE" << EOF
# Feature: $SHORT_NAME

$DESCRIPTION

---

*Generated by dk on $(date -u +"%Y-%m-%dT%H:%M:%SZ")*
EOF

if [[ "$JSON_OUTPUT" == true ]]; then
  cat << EOF
{
  "BRANCH_NAME": "$BRANCH_NAME",
  "FEATURE_DIR": "$(pwd)/$FEATURE_DIR",
  "SPEC_FILE": "$(pwd)/$SPEC_FILE",
  "FEATURE_NUM": "$FEATURE_NUM",
  "SHORT_NAME": "$SHORT_NAME"
}
EOF
else
  echo "Created feature: $FEATURE_NAME"
  echo "  Branch:  $BRANCH_NAME"
  echo "  Spec:    $SPEC_FILE"
  echo "  Dir:     $FEATURE_DIR"
fi
