"""End-to-end integration test for prestaged hydration (T031).

Uses real Postgres via the ``cnpg_conn`` / ``cnpg_cursor`` /
``prestaged_meta_schema`` fixtures from ``tests/conftest.py``.

Fixture ``.dump`` files live in ``tests/fixtures/prestaged/``.  They are
generated by ``tests/fixtures/prestaged/generate_fixtures.sh``.  If absent
the tests skip automatically.

Run with:
    pytest tests/load/test_prestaged_e2e.py -m integration

Tag coverage: [AUDIT] [IDMPT] [VIEWSAFE] [TESTE]
"""

from __future__ import annotations

import datetime as _dt
import os
from pathlib import Path

import pytest

from dk_data.ingestion.prestaged import RunStepOutcome, run_step
from dk_data.ingestion.prestaged_types import LoadStep, PrestagedArtifact
from dk_data.ingestion.transform_runs_writer import TransformRunsWriter

# ---------------------------------------------------------------------------
# Fixture paths
# ---------------------------------------------------------------------------
FIXTURES_DIR = Path(__file__).parent.parent / "fixtures" / "prestaged"

# Canonical fixture dump for the e2e test — a tiny table small enough to
# ship in the repo.  Generated by generate_fixtures.sh.
FIXTURE_DUMP = FIXTURES_DIR / "test_schema" / "test_table" / "01_chunk.dump"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_TEST_SCHEMA = "test_prestaged_schema"
_TEST_TABLE = "test_prestaged_tbl"
_RUN_LABEL = "e2e_test_run_label_" + "0" * 44  # 64 chars total


def _ensure_target(conn: object) -> None:
    """Create the target schema and table in the test DB."""
    with conn.cursor() as cur:  # type: ignore[attr-defined]
        cur.execute(f"CREATE SCHEMA IF NOT EXISTS {_TEST_SCHEMA}")
        cur.execute(f"""
            CREATE TABLE IF NOT EXISTS {_TEST_SCHEMA}.{_TEST_TABLE} (
                id   serial PRIMARY KEY,
                val  text
            )
        """)
    conn.commit()  # type: ignore[attr-defined]


def _drop_target(conn: object) -> None:
    """Tear down after tests."""
    with conn.cursor() as cur:  # type: ignore[attr-defined]
        cur.execute(f"DROP TABLE IF EXISTS {_TEST_SCHEMA}.{_TEST_TABLE}")
        cur.execute(f"DROP SCHEMA IF EXISTS {_TEST_SCHEMA} CASCADE")
    conn.commit()  # type: ignore[attr-defined]


def _count_transform_rows(conn: object, run_label: str, schema: str, table: str) -> int:
    """Count meta.transform_runs rows for the given (run_label, schema, table)."""
    with conn.cursor() as cur:  # type: ignore[attr-defined]
        cur.execute(
            """
            SELECT COUNT(*)
              FROM meta.transform_runs
             WHERE details ->> 'run_label' = %s
               AND details ->> 'target_schema' = %s
               AND details ->> 'target_table' = %s
            """,
            (run_label, schema, table),
        )
        row = cur.fetchone()
    return int(row[0]) if row else 0


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestPrestageDE2E:
    """Integration tests for run_step against a live Postgres."""

    def test_run_step_with_no_artifacts_completes(
        self,
        cnpg_conn: object,
        prestaged_meta_schema: None,
    ) -> None:
        """run_step on a step with zero artifacts records completed (view-safe path)."""
        _ensure_target(cnpg_conn)
        try:
            writer = TransformRunsWriter(cnpg_conn)
            step = LoadStep(
                source_id=f"{_TEST_SCHEMA}.{_TEST_TABLE}",
                target_schema=_TEST_SCHEMA,
                target_table=_TEST_TABLE,
                tier="raw",
                kind="pg_dump",
                artifacts=[],
                depends_on=[],
                wal_mode=False,
            )
            outcome = run_step(cnpg_conn, step, _RUN_LABEL, writer)
            # With no artifacts, dispatch loop is a no-op; COUNT(*) = 0;
            # status = 'completed'.
            assert outcome.status == "completed"
            assert outcome.row_count == 0
            assert outcome.error_detail is None
        finally:
            _drop_target(cnpg_conn)

    def test_run_step_idempotent(
        self,
        cnpg_conn: object,
        prestaged_meta_schema: None,
    ) -> None:
        """A second run_step for the same (run_label, schema, table) is a no-op.

        [IDMPT]: verifies FR-011 — re-run produces zero new INSERTs.
        """
        _ensure_target(cnpg_conn)
        try:
            run_label_idem = _RUN_LABEL[:-5] + "IDEM1"  # distinct from other tests
            writer = TransformRunsWriter(cnpg_conn)
            step = LoadStep(
                source_id=f"{_TEST_SCHEMA}.{_TEST_TABLE}",
                target_schema=_TEST_SCHEMA,
                target_table=_TEST_TABLE,
                tier="raw",
                kind="pg_dump",
                artifacts=[],
                depends_on=[],
                wal_mode=False,
            )

            # First run — inserts a completed row
            outcome1 = run_step(cnpg_conn, step, run_label_idem, writer)
            assert outcome1.status == "completed"

            rows_after_first = _count_transform_rows(
                cnpg_conn, run_label_idem, _TEST_SCHEMA, _TEST_TABLE
            )

            # Second run — is_completed() returns True; no new INSERT
            outcome2 = run_step(cnpg_conn, step, run_label_idem, writer)
            assert outcome2.status == "completed"

            rows_after_second = _count_transform_rows(
                cnpg_conn, run_label_idem, _TEST_SCHEMA, _TEST_TABLE
            )
            assert rows_after_second == rows_after_first, (
                "Idempotent re-run must not insert new meta.transform_runs rows"
            )
        finally:
            _drop_target(cnpg_conn)

    def test_run_step_records_audit_row(
        self,
        cnpg_conn: object,
        prestaged_meta_schema: None,
    ) -> None:
        """run_step always writes a terminal row to meta.transform_runs [AUDIT]."""
        _ensure_target(cnpg_conn)
        try:
            run_label_audit = _RUN_LABEL[:-5] + "AUDT1"
            writer = TransformRunsWriter(cnpg_conn)
            step = LoadStep(
                source_id=f"{_TEST_SCHEMA}.{_TEST_TABLE}",
                target_schema=_TEST_SCHEMA,
                target_table=_TEST_TABLE,
                tier="raw",
                kind="pg_dump",
                artifacts=[],
                depends_on=[],
                wal_mode=False,
            )
            run_step(cnpg_conn, step, run_label_audit, writer)

            # Verify the row is present with status='completed'
            with cnpg_conn.cursor() as cur:  # type: ignore[attr-defined]
                cur.execute(
                    """
                    SELECT status, rows_processed
                      FROM meta.transform_runs
                     WHERE details ->> 'run_label' = %s
                       AND procedure_name = %s
                     ORDER BY run_id DESC
                     LIMIT 1
                    """,
                    (run_label_audit, f"prestaged:{_TEST_SCHEMA}.{_TEST_TABLE}"),
                )
                row = cur.fetchone()

            assert row is not None, "Expected a meta.transform_runs row"
            assert row[0] == "completed"
            assert row[1] >= 0
        finally:
            _drop_target(cnpg_conn)

    @pytest.mark.skipif(
        not FIXTURE_DUMP.exists(),
        reason=(
            f"Fixture dump not found at {FIXTURE_DUMP} — "
            "run tests/fixtures/prestaged/generate_fixtures.sh first"
        ),
    )
    def test_run_step_with_fixture_dump(
        self,
        cnpg_conn: object,
        prestaged_meta_schema: None,
    ) -> None:
        """Restore a real fixture dump and verify rows_processed >= 0.

        This test only runs when the fixture dump file is present (generated
        by ``generate_fixtures.sh``).
        """
        pg_url = os.environ.get("PG_URL") or (
            f"host={os.environ.get('POSTGRES_HOST', 'localhost')} "
            f"port={os.environ.get('POSTGRES_PORT', '5432')} "
            f"user={os.environ.get('POSTGRES_USER', 'postgres')} "
            f"password={os.environ.get('POSTGRES_PASSWORD', 'postgres')} "
            f"dbname={os.environ.get('POSTGRES_DB', 'dk_data_test')}"
        )
        os.environ["PG_URL"] = pg_url

        _ensure_target(cnpg_conn)
        try:
            run_label_dump = _RUN_LABEL[:-5] + "DUMP1"
            writer = TransformRunsWriter(cnpg_conn)

            artifact = PrestagedArtifact(
                path=FIXTURE_DUMP,
                target_schema=_TEST_SCHEMA,
                target_table=_TEST_TABLE,
                tier="raw",
                chunk_index="01",
                size_bytes=FIXTURE_DUMP.stat().st_size,
                sha256=None,
                magic_ok=True,
            )
            step = LoadStep(
                source_id=f"{_TEST_SCHEMA}.{_TEST_TABLE}",
                target_schema=_TEST_SCHEMA,
                target_table=_TEST_TABLE,
                tier="raw",
                kind="pg_dump",
                artifacts=[artifact],
                depends_on=[],
                wal_mode=False,
            )

            outcome = run_step(cnpg_conn, step, run_label_dump, writer)

            assert outcome.status == "completed", (
                f"Expected completed, got {outcome.status}: {outcome.error_detail}"
            )
            assert outcome.row_count >= 0

            # Idempotency: second run produces no new rows
            rows_before = _count_transform_rows(
                cnpg_conn, run_label_dump, _TEST_SCHEMA, _TEST_TABLE
            )
            outcome2 = run_step(cnpg_conn, step, run_label_dump, writer)
            assert outcome2.status == "completed"
            rows_after = _count_transform_rows(
                cnpg_conn, run_label_dump, _TEST_SCHEMA, _TEST_TABLE
            )
            assert rows_after == rows_before, "Re-run must not insert new rows"
        finally:
            _drop_target(cnpg_conn)
