#!/usr/bin/env python3
"""Render per-source Kubernetes Job manifests for the hydrate fan-out.

Horizon 3 / plan §D.1.

Reads ``deploy/hydrate/sources.yaml`` and writes one
``k8s/apps/hydrate/base/job-hydrate-<name>.yaml`` manifest per entry plus
updates ``k8s/apps/hydrate/base/kustomization.yaml`` to list every rendered
manifest alongside the dispatcher + RBAC pieces.

The renderer is idempotent: re-running overwrites existing per-source
Job manifests. Generated files carry the ``generated-by:`` header so a
hand-edit is obvious in diff.

The rendered Job inherits the hardened pattern from ``deploy/jobs/
prestaged-hydrate.yaml`` (H1 PR-01):

  * ``affinity: dk.role In [general]`` + ``NotIn k3s-master-1`` fallback
  * ``priorityClassName: production-critical``
  * ``tolerations: nvidia.com/gpu=true:NoSchedule``
  * ephemeral-storage ``requests: 5Gi`` / ``limits: 20Gi``
  * ``activeDeadlineSeconds`` from descriptor ``sla_seconds`` (default 14400)
  * ``backoffLimit: 2`` (dispatcher does its own cross-Job retry accounting)
  * ``ttlSecondsAfterFinished: 604800`` (7 days — forensics window)

Usage::

    python scripts/render_hydrate_jobs.py
    python scripts/render_hydrate_jobs.py --sources deploy/hydrate/sources.yaml \\
        --out-dir k8s/apps/hydrate/base

Drift-protection: ArgoCD-synced only. Never ``kubectl apply`` the rendered
manifests directly.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from typing import Any, Dict, List

try:
    import yaml
except ImportError:  # pragma: no cover — pyyaml is a runtime dep
    print("error: pyyaml missing; install with `pip install pyyaml`", file=sys.stderr)
    sys.exit(2)


# ---------------------------------------------------------------------------
# Constants — mirror the hardened pattern in deploy/jobs/prestaged-hydrate.yaml
# ---------------------------------------------------------------------------
DEFAULT_SLA_SECONDS = 14400          # 4h — SC-002 ceiling
DEFAULT_BACKOFF_LIMIT = 2             # dispatcher handles higher-level retries
TTL_SECONDS_AFTER_FINISHED = 604800   # 7d forensics window
NAMESPACE = "dk-data-prod"

# Image reference — tag is substituted at deploy time by the ArgoCD image
# updater (kustomize image transformer in k8s/overlays/prod). The string
# ``prod-<sha>`` is the placeholder that matches the base Job.
IMAGE = "ghcr.io/data-kinetic/dk-data:prod-<sha>"

GENERATED_HEADER = """# AUTO-GENERATED by scripts/render_hydrate_jobs.py. DO NOT HAND-EDIT.
# Source: deploy/hydrate/sources.yaml
# Re-render: python scripts/render_hydrate_jobs.py
"""


def _render_job(entry: Dict[str, Any]) -> Dict[str, Any]:
    """Build a Kubernetes Job dict for one sources.yaml entry.

    Uses ``$(RUN_LABEL)`` as a literal in args so the dispatcher can
    substitute the deterministic run-label when it creates the Job (the
    shell the Pod runs does not expand ``$(...)`` — the Downward API does,
    at admission time).
    """
    name = entry["name"]
    source_id = entry["source_id"]
    sla_seconds = int(entry.get("sla_seconds") or DEFAULT_SLA_SECONDS)

    job_name = f"hydrate-{name}"  # `<date>` is appended by the dispatcher

    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
            "name": job_name,
            "namespace": NAMESPACE,
            "labels": {
                "app": "prestaged-hydrate",
                "app.kubernetes.io/name": "prestaged-hydrate",
                "app.kubernetes.io/component": "per-source-hydrate",
                "app.kubernetes.io/part-of": "dk-data",
                "feature": "005-prestaged-hydration",
                "horizon": "3",
                "dk-data/source-id": source_id.replace(".", "-"),
                "product": "dk-data",
                "service": "dk-data",
                "team": "data-platform",
            },
            "annotations": {
                "dk-data/source-id": source_id,
                "dk-data/tier": str(entry.get("tier", 0)),
                "dk-data/sla-seconds": str(sla_seconds),
            },
        },
        "spec": {
            "activeDeadlineSeconds": sla_seconds,
            "backoffLimit": DEFAULT_BACKOFF_LIMIT,
            "ttlSecondsAfterFinished": TTL_SECONDS_AFTER_FINISHED,
            "template": {
                "metadata": {
                    "labels": {
                        "app": "prestaged-hydrate",
                        "app.kubernetes.io/name": "prestaged-hydrate",
                        "app.kubernetes.io/component": "per-source-hydrate",
                        "app.kubernetes.io/part-of": "dk-data",
                        "feature": "005-prestaged-hydration",
                        "dk-data/source-id": source_id.replace(".", "-"),
                        "product": "dk-data",
                        "service": "dk-data",
                        "team": "data-platform",
                    },
                },
                "spec": {
                    "restartPolicy": "OnFailure",
                    "priorityClassName": "production-critical",
                    "securityContext": {
                        "fsGroup": 1000,
                        "runAsGroup": 1000,
                        "runAsNonRoot": True,
                        "runAsUser": 1000,
                        "seccompProfile": {"type": "RuntimeDefault"},
                    },
                    "imagePullSecrets": [{"name": "ghcr-credentials"}],
                    # Node placement — dk-alchemy §2 taxonomy, mirror of
                    # deploy/jobs/prestaged-hydrate.yaml. See that file for
                    # the rationale on the NotIn fallback.
                    "affinity": {
                        "nodeAffinity": {
                            "requiredDuringSchedulingIgnoredDuringExecution": {
                                "nodeSelectorTerms": [
                                    {
                                        "matchExpressions": [
                                            {
                                                "key": "dk.role",
                                                "operator": "In",
                                                "values": ["general"],
                                            }
                                        ]
                                    },
                                    {
                                        "matchExpressions": [
                                            {
                                                "key": "kubernetes.io/hostname",
                                                "operator": "NotIn",
                                                "values": ["k3s-master-1"],
                                            }
                                        ]
                                    },
                                ]
                            }
                        }
                    },
                    "tolerations": [
                        {
                            "key": "nvidia.com/gpu",
                            "operator": "Equal",
                            "value": "true",
                            "effect": "NoSchedule",
                        }
                    ],
                    "containers": [
                        {
                            "name": "hydrate",
                            "image": IMAGE,
                            "imagePullPolicy": "IfNotPresent",
                            "command": ["python", "-m", "dk_data.ingestion.prestaged"],
                            "args": [
                                "--source",
                                source_id,
                                "--run-label",
                                "$(RUN_LABEL)",
                            ],
                            "env": [
                                {"name": "PRESTAGED_ROOT", "value": "/data/prestaged"},
                                {"name": "WAL_PAUSE_HIGH_PCT", "value": "70"},
                                {"name": "WAL_PAUSE_LOW_PCT", "value": "40"},
                                # RUN_LABEL is injected by the dispatcher via
                                # a JSON patch on the Job before create —
                                # kept as an explicit env so kubectl describe
                                # shows what the shell received.
                                {"name": "RUN_LABEL", "value": ""},
                                *_secret_env(
                                    [
                                        "POSTGRES_HOST",
                                        "POSTGRES_PORT",
                                        "POSTGRES_USER",
                                        "POSTGRES_PASSWORD",
                                        "POSTGRES_DB",
                                    ]
                                ),
                            ],
                            "resources": {
                                "requests": {
                                    "cpu": "500m",
                                    "memory": "512Mi",
                                    "ephemeral-storage": "5Gi",
                                },
                                "limits": {
                                    "cpu": "2",
                                    "memory": "4Gi",
                                    "ephemeral-storage": "20Gi",
                                },
                            },
                            "securityContext": {
                                "allowPrivilegeEscalation": False,
                                "capabilities": {"drop": ["ALL"]},
                            },
                            "volumeMounts": [
                                {
                                    "name": "prestaged",
                                    "mountPath": "/data/prestaged",
                                    "readOnly": True,
                                }
                            ],
                        }
                    ],
                    "volumes": [
                        {
                            "name": "prestaged",
                            "hostPath": {
                                "path": "/opt/dk-data-prestaged",
                                "type": "Directory",
                            },
                        }
                    ],
                },
            },
        },
    }


def _secret_env(keys: List[str]) -> List[Dict[str, Any]]:
    """Build a list of env entries sourced from the dk-data-secrets secret."""
    return [
        {
            "name": k,
            "valueFrom": {"secretKeyRef": {"name": "dk-data-secrets", "key": k}},
        }
        for k in keys
    ]


def _write_yaml(path: pathlib.Path, doc: Dict[str, Any]) -> None:
    """Write ``doc`` to ``path`` with the generated-by header."""
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=120)
    path.write_text(GENERATED_HEADER + body)


def _render_kustomization(out_dir: pathlib.Path, job_files: List[str]) -> None:
    """Emit kustomization.yaml listing the dispatcher + RBAC + per-source Jobs."""
    # Ordering rule: RBAC first so ArgoCD creates ServiceAccount before
    # dispatcher Job references it. Per-source Jobs follow in sorted order.
    resources = [
        "hydrate-dispatcher-serviceaccount.yaml",
        "hydrate-dispatcher-rbac.yaml",
        "job-hydrate-dispatch.yaml",
    ] + sorted(job_files)

    doc = {
        "apiVersion": "kustomize.config.k8s.io/v1beta1",
        "kind": "Kustomization",
        "namespace": NAMESPACE,
        "resources": resources,
    }
    path = out_dir / "kustomization.yaml"
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    path.write_text(GENERATED_HEADER + body)


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="render_hydrate_jobs.py",
        description=(
            "Render per-source hydrate Job manifests from deploy/hydrate/sources.yaml"
        ),
    )
    parser.add_argument(
        "--sources",
        default="deploy/hydrate/sources.yaml",
        help="Path to the source registry YAML (default: deploy/hydrate/sources.yaml)",
    )
    parser.add_argument(
        "--out-dir",
        default="k8s/apps/hydrate/base",
        help="Directory to write job-hydrate-<name>.yaml files",
    )
    parser.add_argument(
        "--print-only",
        action="store_true",
        default=False,
        help="Print rendered YAML to stdout without writing files (dry-run).",
    )
    args = parser.parse_args(argv)

    sources_path = pathlib.Path(args.sources)
    out_dir = pathlib.Path(args.out_dir)

    if not sources_path.exists():
        print(f"error: {sources_path} does not exist", file=sys.stderr)
        return 2

    doc = yaml.safe_load(sources_path.read_text()) or {}
    entries = doc.get("sources", []) or []
    if not isinstance(entries, list) or not entries:
        print(
            f"error: {sources_path} has no `sources:` list or it's empty",
            file=sys.stderr,
        )
        return 2

    job_files: List[str] = []
    for entry in entries:
        if not isinstance(entry, dict):
            print(f"error: malformed entry {entry!r}", file=sys.stderr)
            return 2
        name = entry.get("name")
        if not name:
            print(f"error: entry missing `name`: {entry!r}", file=sys.stderr)
            return 2

        job_doc = _render_job(entry)
        job_path = out_dir / f"job-hydrate-{name}.yaml"
        if args.print_only:
            print("---")
            print(yaml.safe_dump(job_doc, sort_keys=False))
        else:
            _write_yaml(job_path, job_doc)
        job_files.append(job_path.name)

    if not args.print_only:
        _render_kustomization(out_dir, job_files)
        print(
            f"Rendered {len(job_files)} per-source Job manifest(s) into {out_dir}/",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":  # pragma: no cover — CLI entry point
    sys.exit(main(sys.argv[1:]))
