apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dk-data-secrets
  labels:
    app.kubernetes.io/name: dk-data
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: doppler-operator
spec:
  tokenSecret:
    name: doppler-token-secret
    key: serviceToken
  project: dk-data
  config: prd
  managedSecret:
    name: dk-data-secrets
    type: Opaque
  resyncSeconds: 300
