-- =============================================================================
-- Migration 086: CMS PUF Agent Silver Table Schema Fixes
-- Feature: 019-cms-puf-platform-reconciliation
-- =============================================================================
-- Fixes discovered during agent quality review:
-- 1. All 6 hcs_silver agent tables are missing `updated_at` (agents set it in
--    ON CONFLICT UPDATE, causing runtime errors).
-- 2. hcs_silver.service_lines UNIQUE (npi, service_line, _source_year) does not
--    match ON CONFLICT (npi) in write_results — intent is one service line per NPI.
-- 3. hcs_silver.idn_hierarchy UNIQUE (child_npi, parent_organization) does not
--    match ON CONFLICT (child_npi) — intent is one parent per child NPI.
-- 4. hcs_silver.referral_network missing relationship_strength column (returned
--    by LLM, stored in output dict, never written to a queryable column).
-- 5. hcs_silver.equipment_inventory missing inferred_equipment column (same issue).
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Add updated_at to all 6 hcs_silver agent tables
-- ---------------------------------------------------------------------------

ALTER TABLE hcs_silver.service_lines
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE hcs_silver.idn_hierarchy
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE hcs_silver.referral_network
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE hcs_silver.verified_contacts
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE hcs_silver.staffing_decomposition
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE hcs_silver.equipment_inventory
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- ---------------------------------------------------------------------------
-- 2. Fix hcs_silver.service_lines UNIQUE constraint
--    Old: UNIQUE (npi, service_line, _source_year)  — allows multiple rows per NPI
--    New: UNIQUE (npi)                               — one primary service line per NPI
-- ---------------------------------------------------------------------------

DO $$
BEGIN
    -- Drop the old composite constraint (name is auto-generated by PostgreSQL)
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'hcs_silver'
          AND table_name = 'service_lines'
          AND constraint_type = 'UNIQUE'
          AND constraint_name != 'service_lines_pkey'
          AND constraint_name NOT LIKE '%_npi_key'
    ) THEN
        EXECUTE (
            SELECT 'ALTER TABLE hcs_silver.service_lines DROP CONSTRAINT ' || constraint_name
            FROM information_schema.table_constraints
            WHERE table_schema = 'hcs_silver'
              AND table_name = 'service_lines'
              AND constraint_type = 'UNIQUE'
              AND constraint_name != 'service_lines_pkey'
              AND constraint_name NOT LIKE '%_npi_key'
            LIMIT 1
        );
    END IF;
END;
$$;

ALTER TABLE hcs_silver.service_lines
    ADD CONSTRAINT IF NOT EXISTS service_lines_npi_key UNIQUE (npi);

-- ---------------------------------------------------------------------------
-- 3. Fix hcs_silver.idn_hierarchy UNIQUE constraint
--    Old: UNIQUE (child_npi, parent_organization)  — allows multiple parents per child
--    New: UNIQUE (child_npi)                        — one parent per child NPI
-- ---------------------------------------------------------------------------

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'hcs_silver'
          AND table_name = 'idn_hierarchy'
          AND constraint_type = 'UNIQUE'
          AND constraint_name != 'idn_hierarchy_pkey'
          AND constraint_name NOT LIKE '%_child_npi_key'
    ) THEN
        EXECUTE (
            SELECT 'ALTER TABLE hcs_silver.idn_hierarchy DROP CONSTRAINT ' || constraint_name
            FROM information_schema.table_constraints
            WHERE table_schema = 'hcs_silver'
              AND table_name = 'idn_hierarchy'
              AND constraint_type = 'UNIQUE'
              AND constraint_name != 'idn_hierarchy_pkey'
              AND constraint_name NOT LIKE '%_child_npi_key'
            LIMIT 1
        );
    END IF;
END;
$$;

ALTER TABLE hcs_silver.idn_hierarchy
    ADD CONSTRAINT IF NOT EXISTS idn_hierarchy_child_npi_key UNIQUE (child_npi);

-- ---------------------------------------------------------------------------
-- 4. Add relationship_strength to referral_network
-- ---------------------------------------------------------------------------

ALTER TABLE hcs_silver.referral_network
    ADD COLUMN IF NOT EXISTS relationship_strength TEXT;

-- ---------------------------------------------------------------------------
-- 5. Add inferred_equipment to equipment_inventory
-- ---------------------------------------------------------------------------

ALTER TABLE hcs_silver.equipment_inventory
    ADD COLUMN IF NOT EXISTS inferred_equipment TEXT;

-- ---------------------------------------------------------------------------
-- 6. Add missing practice-location columns to hcs_raw.cms_nppes
--    Required by the contact_verification and idn_hierarchy agents
-- ---------------------------------------------------------------------------
ALTER TABLE hcs_raw.cms_nppes
    ADD COLUMN IF NOT EXISTS provider_business_mailing_address_city_name TEXT,
    ADD COLUMN IF NOT EXISTS provider_business_mailing_address_state_name TEXT,
    ADD COLUMN IF NOT EXISTS provider_business_mailing_address_postal_code TEXT,
    ADD COLUMN IF NOT EXISTS provider_business_practice_location_address_telephone_number TEXT,
    ADD COLUMN IF NOT EXISTS provider_business_practice_location_address_fax_number TEXT,
    ADD COLUMN IF NOT EXISTS provider_first_line_business_practice_location_address TEXT,
    ADD COLUMN IF NOT EXISTS provider_second_line_business_practice_location_address TEXT,
    ADD COLUMN IF NOT EXISTS provider_business_practice_location_address_city_name TEXT,
    ADD COLUMN IF NOT EXISTS provider_business_practice_location_address_postal_code TEXT,
    ADD COLUMN IF NOT EXISTS provider_business_practice_location_address_country_code TEXT;

-- ---------------------------------------------------------------------------
-- 7. Add cms_physician_puf_services (NPI x HCPCS level) for equipment_inventory agent
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hcs_raw.cms_physician_puf_services (
    id                          BIGSERIAL PRIMARY KEY,
    npi                         TEXT NOT NULL,
    hcpcs_code                  TEXT NOT NULL,
    hcpcs_description           TEXT,
    place_of_service            TEXT,
    line_srvc_cnt               NUMERIC(18,2),
    bene_unique_cnt             INTEGER,
    bene_day_srvc_cnt           INTEGER,
    average_medicare_allowed_amt NUMERIC(18,2),
    average_submitted_chrg_amt  NUMERIC(18,2),
    average_medicare_payment_amt NUMERIC(18,2),
    average_medicare_stnd_amt   NUMERIC(18,2),
    _source_year                INTEGER NOT NULL,
    _source_hash                TEXT NOT NULL,
    _source_file                TEXT,
    _loaded_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (npi, hcpcs_code, place_of_service, _source_year)
);

-- ---------------------------------------------------------------------------
-- 8. Add cms_cost_reports_puf_lines (worksheet lines) for staffing_decomposition agent
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hcs_raw.cms_cost_reports_puf_lines (
    id                          BIGSERIAL PRIMARY KEY,
    provider_id                 TEXT NOT NULL,
    facility_type               TEXT,
    line_item_code              TEXT NOT NULL,
    line_item_description       TEXT,
    reported_hours_fte          NUMERIC(12,2),
    total_salaries              NUMERIC(18,2),
    source_year                 INTEGER,
    _source_year                INTEGER NOT NULL,
    _source_hash                TEXT NOT NULL,
    _source_file                TEXT,
    _loaded_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (provider_id, line_item_code, _source_year)
);

COMMIT;
