apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-ghcr
  labels:
    app.kubernetes.io/name: dk-data
    app.kubernetes.io/component: registry-credentials
    app.kubernetes.io/managed-by: doppler-operator
spec:
  tokenSecret:
    name: doppler-token-secret
    key: serviceToken
  project: dk-data-applications
  config: prd
  managedSecret:
    name: ghcr-credentials
    type: kubernetes.io/dockerconfigjson
  secrets:
    - GHCR_DOCKERCONFIGJSON
  processors:
    GHCR_DOCKERCONFIGJSON:
      asName: .dockerconfigjson
      type: base64
  resyncSeconds: 300
