apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: job-trigger-pdb
  labels:
    app.kubernetes.io/name: job-trigger
    app.kubernetes.io/part-of: dk-data
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: job-trigger
